baseURL = "https://HaHaHa326.github.io"
title = "我的博客"
theme = "hyde"

# 语言设置
languageCode = "zh-CN"
defaultContentLanguage = "zh"



# 启用分类和标签
[taxonomies]
  category = "categories"
  tag = "tags"

# 网站参数
[params]
  description = "分享技术与生活，记录成长与思考"
  copyright = "© 2026 我的博客. 保留所有权利"
  avatar = "/images/小八.jpg"  # 头像路径

# 社交链接配置 - 将显示在版权上方
[[params.social]]
  name = "GitHub"
  url = "https://github.com/HaHaHa326"


[[params.social]]
  name = "邮箱"
  url = "cchen4661@163.com"


# 导航菜单配置

[[menu.main]]
  name = "RF"
  url = "/RF/"
  weight = 2
[[menu.main]]
  name = "other"
  url = "/other/"
  weight = 3
[markup]
  [markup.goldmark]
    [markup.goldmark.renderHooks]
      [markup.goldmark.renderHooks.image]
        enableDefault = true   # 启用默认的图片渲染钩子
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false  # (可选) 让图片不被自动包裹在<p>标签中
